language: python
python:
  - "2.6"
  - "2.7"
  # Not quite ready for prime time...
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy"
# command to install dependencies
install:
  - pip install coveralls
  # Need to do this since coverage is broken in travis https://github.com/travis-ci/travis-ci/issues/4866
  - pip install 'coverage<4'
  - pip install pytest>=3.0.2 pytest-cov
# command to run tests
script: py.test --cov voluptuous voluptuous/tests/tests.py
after_success:
  - coveralls
